id: I76475646
legacy_id: P003194
ocr_import_info:
  bdrc_scan_id: W19884
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T09:14:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:44:10.901661+00:00'
last_modified: 2022-08-30 23:46:42.726986
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19884
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW19884
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ལྷ་བཟང་བླ་མ་རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.6231882367176519
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I1PD89125:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD89125
      total_pages: 580
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1PD89125.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5855964216758252
    legacy_id: v004
  I1PD89126:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD89126
      total_pages: 590
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1PD89126.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6101854436983792
    legacy_id: v005
  I1PD89124:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD89124
      total_pages: 596
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD89124.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6073473873983163
    legacy_id: v003
  I1PD89122:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD89122
      total_pages: 598
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD89122.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6395075075239083
    legacy_id: v001
  I1PD89123:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD89123
      total_pages: 584
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD89123.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6748522789296113
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
