id: I76475646
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:18:19+00:00'
last_modified: '2022-06-07T18:19:28.372337+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19884
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4AAA:
      image_group_id: I1PD89122
      title: ''
      total_pages: 598
      order: 1
      base_file: 4AAA.txt
    73B7:
      image_group_id: I1PD89123
      title: ''
      total_pages: 584
      order: 2
      base_file: 73B7.txt
    08BA:
      image_group_id: I1PD89124
      title: ''
      total_pages: 596
      order: 3
      base_file: 08BA.txt
    3C10:
      image_group_id: I1PD89125
      title: ''
      total_pages: 580
      order: 4
      base_file: 3C10.txt
    C5B4:
      image_group_id: I1PD89126
      title: ''
      total_pages: 590
      order: 5
      base_file: C5B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
