id: P003194
initial_creation_type: ocr
source_metadata:
  id: bdr:W19884
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  volumes:
    c652ebf403474f6fbf60625943268b5a:
      image_group_id: I1PD89122
      title: ''
      volume_number: 1
      total_pages: 598
    49756bccfbcb422e9b2b0bd81b10bf81:
      image_group_id: I1PD89123
      title: ''
      volume_number: 2
      total_pages: 584
    8481e4930b944a26b8a070f00437e779:
      image_group_id: I1PD89124
      title: ''
      volume_number: 3
      total_pages: 596
    ee56d99373084eadbdf51dd21907fcc9:
      image_group_id: I1PD89125
      title: ''
      volume_number: 4
      total_pages: 580
    fbdb363da1e44890a05234e8fc7df116:
      image_group_id: I1PD89126
      title: ''
      volume_number: 5
      total_pages: 590
